#!/usr/bin/python3

"""
Connect to reversebeacon.net and print only the DL/ON/PA spots

Copyright (C) 2021 Christoph Berg DF7CB
License: MIT
"""

import socket
import select
import re

#host = "arcluster.reversebeacon.net"
host = "telnet.reversebeacon.net"
port = 7000

print(f"Connecting to {host}:{port} ...", flush=True)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((host, port))

s.send(b"DF7CB\r\n")

# DX de DF2CK-#:   14009.8  EA8VI          CW     3 dB  23 WPM  CQ      0838Z
# DX de IK4VET-#: 14022.90  9A2N           CW    19 dB  29 WPM  CQ      0940Z
# DX de LZ7AA-#:   14070.8  IZ4ISM         PSK31 19 dB  31 BPS  CQ      0936Z
# DX de G4ZFE-#:   14071.0  IZ5GUB         PSK31 20 dB  31 BPS  CQ      0942Z
re1 = re.compile('DX de ')
re2 = re.compile('DX de (D[A-R]|P[A-I]|O[N-T])')

def dx(msg):
    line = msg.decode(encoding='UTF-8', errors='replace')
    if re.match(re1, line):
        if re.match(re2, line):
            print(line, flush=True)
    else:
        print(line, flush=True)

buf = b""
while True:
    r, w, x = select.select([s], [], [], None)
    if s in r:
        buf += s.recv(1024)
        while b"\r\n" in buf:
            line, sep, buf = buf.partition(b"\r\n")
            dx(line)
