#!/bin/sh

# export sdrangel settings to files

set -eux

API="http://127.0.0.1:8091/sdrangel"
DEVICESET="$API/deviceset"

# settings
curl -f > config.json $API/config

# RX device set
curl -f > rxdevice.json $DEVICESET/0/device/settings
curl -f > rxspectrum.json $DEVICESET/0/spectrum/settings
curl -f > rx0.json $DEVICESET/0/channel/0/settings
curl -f > rx1.json $DEVICESET/0/channel/1/settings
curl -f > rx2.json $DEVICESET/0/channel/2/settings

# TX device set
curl -f > txdevice.json $DEVICESET/1/device/settings
curl -f > txspectrum.json $DEVICESET/1/spectrum/settings
curl -f > tx0.json $DEVICESET/1/channel/0/settings
curl -f > tx1.json $DEVICESET/1/channel/1/settings
curl -f > tx2.json $DEVICESET/1/channel/2/settings
