#!/usr/bin/python3

"""
Connect to a DX cluster and store all spots in a PostgreSQL database

Copyright (C) 2021 Christoph Berg DF7CB
License: MIT
"""

"""
create table dxcluster (
  start timestamptz(0) not null default now(),
  spotter text not null,
  qrg numeric not null,
  dx text not null,
  msg text,
  loc text
);
"""

import psycopg2
import socket
import select
import re

conn = psycopg2.connect("service=cb application_name=pgdx")
cur = conn.cursor()

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("db0sue.de", 8000))

s.send(b"DF7CB\r\n")

# DX de IK5WOB:     3520.0  IQ5PJ        Coltano Marconi Award          1656Z JN53
# DX de W2CCC:     50313.0  WA5TKU       em13<>fn23 ft8                 1656Z FN23
# DX de EA5IKT:     7057.0  EA4TL        dme-10059 cq                   1656Z
# DX de ON4PE:     21074.0  PY4PDO       Db -7                          1656Z JO10
# DX de EA1JW:      7062.0  EA1FHQ       EO-1467 DME-33043              1656Z
# DX de F4CXO:     28019.9  PP5VZ        JN26PP<>GG52RJ 529             1657Z
# DX de EA5D:      14081.0  N8JJM        FT4 -11 IM99XX<>EN72           1657Z IM99
# DX de KE1DX:     21029.8  LU/CE3CT                                    1657Z FN31

re1 = re.compile('DX de ([^ -#]+)(?:-#)?: +([\d.]+) +([^ ]+) +(\S(?:.*\S)?)? +\d\d\d\dZ *(.*[^\a ])?')

def dx(msg):
    try:
        line = msg.decode(encoding='UTF-8', errors='replace')
        if m := re.match(re1, line):
            print(m.groups())
            cur.execute('insert into dxcluster (spotter, qrg, dx, msg, loc) values (%s, %s, %s, %s, %s)', m.groups())
            conn.commit()
        else:
            print("Could not handle", line)
    except Exception as e:
        print("Something went wrong with", msg, e)
        conn.rollback()


while True:
    r, w, x = select.select([s], [], [], None)
    buf = b""
    if s in r:
        buf += s.recv(1024)
        while b"\r\n" in buf:
            pos = buf.index(b"\r\n")
            dx(buf[:pos])
            buf = buf[pos+2:]
