#!/usr/bin/python3

import psycopg2
import psycopg2.extras
import re
import sys

conn = psycopg2.connect("service=cb")
cur = conn.cursor(cursor_factory = psycopg2.extras.DictCursor)

for line in sys.stdin:
    l = line.strip()
    m = re.search("^[0-9]+$", l)
    if m:
        qsl = qsls[int(l)]
        if qsl['qsltx'] == 'J':
            cur.execute("""UPDATE log SET qslrx = 'J' WHERE (start, call) = (%s, %s)""",
                    (qsl['start'], qsl['call']))
            conn.commit()
        if qsl['qsltx'] == 'W':
            cur.execute("""UPDATE log SET qsltx = 'J', qslrx = 'W' WHERE (start, call) = (%s, %s)""",
                    (qsl['start'], qsl['call']))
            conn.commit()
        else:
            assert(0)

    else:
        cur.execute("""SELECT row_number() over () as n, * FROM log WHERE call ~* %s ORDER BY start""", (l,))
        qsls = ['']
        for rec in cur.fetchall():
            qsls.append(rec)
            print(str(rec['n']) + ':',
                    rec['start'], rec['call'], rec['qrg'], rec['mode'],
                    rec['rsttx'], rec['rstrx'],
                    rec['qsltx'], rec['qslrx'])
